@startuml usecase

left to right direction

:visitor: as v
:player: as p

p --|> v

package Authentification {
    usecase "Log In" as li
    usecase "Log Out" as lo
    usecase "Register" as rgt
}

package Fonctionnalities {
    package Pokedex {
        usecase "Search for a team" as sfatm
        usecase "View all teams" as vatm
        usecase "Search for a type" as sfatp
        usecase "View all types" as vatp
        usecase "Search for a Pokémon" as sfap
        usecase "View all Pokémon" as vap
    }

    package Team {
        usecase "Create a team" as cat
        usecase "Add a Pokémon" as ap
        usecase "Rename a Pokémon" as rap
        usecase "Delete a Pokémon" as dap
        usecase "Rename a team" as rat
        usecase "Delete a team" as dat
    }
}

v --> sfatm
v -->vatm
v --> sfatp
v --> vatp
v --> sfap
v --> vap
v -up-> rgt

p -up-> li
p -up-> lo
p -->cat
p --> ap
p --> rap
p --> dap
p --> rat
p --> dat
@endum
