@startuml usecase

left to right direction

:visitor: as v
:player: as p

p --|> v

package Authentification {
    usecase "Access a login form" as alf
    usecase "Access a registration form" as arf
}

package "Fonctionnalities" {
    package Pokedex {
        usecase "Search for a team" as sfatm
        usecase "View all teams" as vatm
        usecase "Search for a type" as sfatp
        usecase "View all types" as vatp
        usecase "Search for a Pokémon" as sfap
        usecase "View all Pokémon" as vap
    }

    package Team {
        usecase "Delete a Pokémon" as dap
        usecase "Rename a Pokémon" as rap
        usecase "Add a Pokémon" as ap
        usecase "Delete a team" as dat
        usecase "Rename a team" as rat
        usecase "Create a team" as cat
    }
}

v --> sfatm
v -->vatm
v --> sfatp
v --> vatp
v --> sfap
v --> vap
v -up-> arf

p -up-> alf
p --> dap
p --> rap
p --> ap
p --> dat
p --> rat
p -->cat
@endum
